spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mystore
    username: postgres
    password: Viking07
  flyway:
    baseline-on-migrate: true
server:
  hostname: localhost
  port: ${PORT:8080}
mail:
  server:
    host: smtp.gmail.com
    port: 587
    username: litvak.test@gmail.com
    password: Helloworld78

